### ISSUE TITLE
Poison-Ivy-Reload值得期待

### ISSUE THREAD

**Issue by blackhat1987** [killeven/Poison-Ivy-Reload#1]
Poison-Ivy这个工具太值得期待了，不知道您是用得什么语言复刻的？看到你提及anskya，是不是用的delphi，现在Poison-Ivy在高版本系统中不怎么好用了，期待您的大作。。。

**Comment by killeven** [comment]
我是使用汇编，c语言，还有delphi联合开发的，目前正在复刻2.32的功能.

**Comment by blackhat1987** [comment]
@killeven 谢谢回复啊，我只会一点delphi，毕竟业余中的业余。。。 祝早日实现想要实现的！
