### ISSUE TITLE
Poison Ivy 2.3.2-远程缓冲区溢出，这个版本有解决吗

### ISSUE THREAD

**Issue by ghost** [killeven/Poison-Ivy-Reload#2]
Poison Ivy 2.3.2-远程缓冲区溢出，这个版本有解决吗

**Comment by killeven** [comment]
这是我重写的版本啊…………------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;嘻嘻嘻&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月7日(星期五) 晚上9:39
收件人:&nbsp;&quot;killeven/Poison-Ivy-Reload&quot;<Poison-Ivy-Reload@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[killeven/Poison-Ivy-Reload] Poison Ivy 2.3.2-远程缓冲区溢出，这个版本有解决吗 (#2)
