### ISSUE TITLE
how to add a file-transfer function with a few changes?

### ISSUE THREAD

**Issue by fadinglr** [killeven/Poison-Ivy-Reload#4]
Dear author，
    Thank you for the great work you've done, I am a newer at rat developing who is very interested in you project. Now I am trying to understand your code first, and I want to add a file-transfer function to it. As I found in the project, I think this function can be joined in the cmd_shell function.
Let's see this code:
```
  // cmd_shell data
  if (cmd == CMD_CMDSHELL_DATA) {
    if (extra_data()->state & STATE_CMD_SHELL) {
      return xcmd_shell_execute(s, (const char *)((uint32_t *)data));
    }
  }
```
If the cmd_shell data starts with '.download' or '.upload', the i can start a new thread to handle the file operation.
But this is c style way, your code is much more complicated as it is written in asm, and the client is also a difficult language for me to understand.So I do not know whether i am right or not. And if i handle '.download c:\windows\test.txt' as a file downloading command, how should I handle it on the client side?

Looking forward to your reply.
Sincerely.

**Comment by killeven** [comment]
I designed it with single-threaded mode. For example, if you want add download function.
if (cmd == CMD_DOWNLOAD_DATA) {
  // parse filename name, pos, data from input data
  write_file
}

My english is poor,hope you can understand.
